FROM python:3.11-slim
WORKDIR /ml
RUN pip install --no-cache-dir mlflow==2.16.2
VOLUME /mlruns
EXPOSE 5000
CMD ["mlflow","server","--host","0.0.0.0","--port","5000","--backend-store-uri","sqlite:///mlflow.db","--default-artifact-root","/mlruns"]
